# Part 1

The file "Purchase_Data.csv" contains purchase data at a Chinese supermarket for various products.  Read this csv into a dataframe called df_data and use the head() method to check that you have read in the data correctly. Make sure you import pandas.

In [25]:
#Write your code here
import pandas as pd

df_data = pd.read_csv("Data/Purchase_Data.csv")

df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Use the dtypes attribute to view how each column is stored

In [26]:
#Write your code here
df_data.dtypes

invoice_number    float64
invoice_time       object
store_id           object
product_id          int64
category_id         int64
num_item          float64
price             float64
dtype: object

Slice the first two columns using .loc and store the result in a variable called result_1.

Slice the first two columns using .loc and store the result in a variable called result_1.

In [27]:
#Write you code here
# Slice the first two columns by column label using .loc
result_1 = df_data.loc[:, "invoice_number":"invoice_time"]

result_1.head() 

result_1 = df_data.loc[:, df_data.columns[:2]]

Slice the first two rows using .loc and store the result in a variable called result_2.

In [28]:
#Write you code here
result_2 = df_data.loc[0:1]

# View the result
result_2

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0

Slice the first four rows and the first five columns and store the result in a variable called result_3.

In [29]:
#Write your code here
# Slicing using positional indexing (.iloc)
result_3 = df_data.iloc[:4, :5]

# View the result
result_3

# Using label/index slicing with .loc
result_3 = df_data.loc[0:3, df_data.columns[:5]]

Slice rows 0,4,6 and columns invoice time and price and store the result in variable called result_4.

In [30]:
#Write your code here

# Slice specific rows [0, 4, 6] and specific columns ['invoice_time', 'price'] using .loc
result_4 = df_data.loc[[0, 4, 6], ["invoice_time", "price"]]

# View the result
result_4

    invoice_time  price
0  7/15/15 10:45    2.0
4  7/15/15 12:16    6.0
6  7/15/15 15:28    2.0

Store the number rows in a variable called num_rows.

In [31]:

# Store the total number of rows in num_rows
num_rows = df_data.shape[0]

# Alternatively:
# num_rows = len(df_data)

print(num_rows)

5382

Print out the last row of the data to dataframe. **Hint:** use the variable num_rows from the previous exercise.

In [32]:
#Write your code here

# Print the last row using num_rows with .loc
df_data.loc[[num_rows - 1]]

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
5381,2.020000e+11,9/5/15 23:38,G619,23030206,210101,1.0,2.0

# Part 2

Compute the average and max price charged.  Store the results in variables called avg_price and max_price

In [33]:
#Write your code here

# Calculate the average and maximum price
avg_price = df_data["price"].mean()
max_price = df_data["price"].max()

# View the results
print(f"Average Price: {avg_price:.4f}")
print(f"Maximum Price: {max_price:.2f}")

Average Price: 3.1921
Maximum Price: 6.01

Compute the average price and average number of items purchased with only a single call to the mean() method. Store these averages in avg_price and avg_num_items.

In [34]:
#Write you code here

# Compute both averages with a single call to mean()
averages = df_data[["price", "num_item"]].mean()

# Extract the individual average values
avg_price = averages["price"]
avg_num_items = averages["num_item"]

# View the results
print(f"Average Price: {avg_price:.4f}")
print(f"Average Num Items: {avg_num_items:.4f}")

Average Price: 3.1921
Average Num Items: 1.2983

Create a column called "total", which is the product of the price and num_item columns.

In [35]:
#Write your code here

# Create the 'total' column by multiplying 'price' and 'num_item'
df_data["total"] = df_data["price"] * df_data["num_item"]

# Verify the new column
df_data[["price", "num_item", "total"]].head()

   price  num_item  total
0    2.0       1.0    2.0
1    2.0       1.0    2.0
2    2.0       1.0    2.0
3    6.0       1.0    6.0
4    6.0       1.0    6.0

What is the avgerage price of the three most expensive purchases?

In [36]:
#Write your code here
# Option 1: Based on individual item unit price ('price')
top_3_prices = df_data.nlargest(3, "price")["price"].mean()
print(f"Average unit price: {top_3_prices:.4f}")

# Option 2: Based on total purchase cost ('total' = price * num_item)
top_3_totals = df_data.nlargest(3, "total")
avg_unit_price_of_top_totals = top_3_totals["price"].mean()
avg_total_cost_of_top_totals = top_3_totals["total"].mean()

Average unit price: 6.0033

How many different products are there?

In [37]:
#Write your code here

# Count the number of unique product IDs
num_unique_products = df_data["product_id"].nunique()

print(num_unique_products)

53

Find the difference between the mean and median of the column total.  Use the describe() method and then index the dataframe it returns.

In [38]:
#Write your code here

# Generate summary statistics for the 'total' column
total_stats = df_data["total"].describe()

# Index the Series to get mean and median (50%)
mean_total = total_stats["mean"]
median_total = total_stats["50%"]

# Calculate the difference
diff = mean_total - median_total

print(diff)

0.9318078781127839

Use the drop() method to delete the column total from the dataframe df_data.

In [39]:
#Write your code here

# Drop the 'total' column and save changes to df_data
df_data = df_data.drop(columns=["total"])

# Alternatively, use inplace=True:
# df_data.drop(columns=['total'], inplace=True)

# Verify the column has been removed
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price
0,2.020000e+11,7/15/15 10:45,G816,7000300,210101,1.0,2.0
1,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
2,2.020000e+11,7/15/15 12:16,G816,7070884,70203,1.0,2.0
3,2.020000e+11,7/15/15 12:16,G816,7070891,70401,1.0,6.0
4,2.020000e+11,7/15/15 12:16,G816,7090363,70401,1.0,6.0

Let's dig a little deeper into the data set and answer some basic question.

In [40]:
#Write your code here

First, covert the column invoice time to a datetime column. Print out the new column types to make sure this was done correctly

In [41]:
#Write your code here

# Convert the 'invoice_time' column to datetime
df_data["invoice_time"] = pd.to_datetime(
    df_data["invoice_time"], format="%m/%d/%y %H:%M"
)

# Print out the new column data types
print(df_data.dtypes)

invoice_number           float64
invoice_time      datetime64[ns]
store_id                  object
product_id                 int64
category_id                int64
num_item                 float64
price                    float64
dtype: object

Next, let's create columns called "DOW" and "Month", which store the corresponding weekday and month of the invoice respectively.  Print the head of the dataframe to make sure this was done correctly.

In [42]:
#Write your code here

# Create DOW (Day of Week) and Month columns using datetime accessor dt
df_data["DOW"] = df_data["invoice_time"].dt.day_name()
df_data["Month"] = df_data["invoice_time"].dt.month_name()

# Display the first few rows to verify
df_data.head()

,invoice_number,invoice_time,store_id,product_id,category_id,num_item,price,DOW,Month
0,2.020000e+11,2015-07-15 10:45:00,G816,7000300,210101,1.0,2.0,Wednesday,July
1,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,July
2,2.020000e+11,2015-07-15 12:16:00,G816,7070884,70203,1.0,2.0,Wednesday,July
3,2.020000e+11,2015-07-15 12:16:00,G816,7070891,70401,1.0,6.0,Wednesday,July
4,2.020000e+11,2015-07-15 12:16:00,G816,7090363,70401,1.0,6.0,Wednesday,July

Create a variable called num_purchases_wed, which stores the number of purchases made on Wednesday?  You should use value_counts and then index the series it return.

In [43]:
#Write your code here

# Get count of purchases per day of the week and index for 'Wednesday'
num_purchases_wed = df_data["DOW"].value_counts()["Wednesday"]

print(num_purchases_wed)

959

# Part 3

In this set of practice exercises, we will be working with a demographic data regarding the passengers aboard the Titanic.  Read in the data frame and use the head() method to check that it was read in correctly.

In [44]:
#Write your code here

import pandas as pd

# Read in the Titanic dataset
df_titanic = pd.read_csv("Data/titanic.csv")

df_titanic.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Use the rename method to change the column "Name" to "Passenger_Name" and the column "Ticket" to "Ticket_Num".

In [45]:
#Write your code here

df_titanic = df_titanic.rename(
    columns={"Name": "Passenger_Name", "Ticket": "Ticket_Num"}
)

# Alternatively, using inplace=True:

df_titanic.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Change the index of the df_titanic to the column PasengerID.

In [46]:
#Write your code here

df_titanic = df_titanic.set_index("PassengerId")

# df_titanic.set_index('PassengerId', inplace=True)

df_titanic.head()

,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,
892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

Select the name of passenger 896

In [47]:
#Write your code here

passenger_896_name = df_titanic.loc[896, "Passenger_Name"]

print(passenger_896_name)

Hirvonen, Mrs. Alexander (Helga E Lindqvist)

Change the index back to row numbers but making sure that we don't lose the PassengerId column.

In [48]:
#Write your code here

df_titanic = df_titanic.reset_index()

# df_titanic.reset_index(inplace=True)

df_titanic.head()

,PassengerId,Pclass,Passenger_Name,Sex,Age,SibSp,Parch,Ticket_Num,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

How many missing entries are there in the Age column? Use the isnull() method and recall than Booleans are exactly like 1s (True) and 0s (False).

In [49]:
#Write you code here

missing_age_count = df_titanic["Age"].isnull().sum()

print(missing_age_count)

86

Compute the avg age of passengers ignoring the missing data.

In [50]:
#Write your code here

avg_age = df_titanic["Age"].mean()

print(avg_age)

30.272590361445783

Using the fillna() method replace the missing values in the Age column with the mean.

In [51]:
#Write your code here

# Calculate the mean age
mean_age = df_titanic["Age"].mean()

# Replace missing values in the 'Age' column with the mean
df_titanic["Age"] = df_titanic["Age"].fillna(mean_age)

# Verify that there are no remaining missing values
print(df_titanic["Age"].isnull().sum())

0

What is the average age of the 5 oldest passengers? The reset_index method will be helpful here.

In [52]:
#Write your code here

top_5_oldest = df_titanic.sort_values(by="Age", ascending=False).reset_index(
    drop=True
)

avg_oldest_5 = top_5_oldest.head(5)["Age"].mean()

print(avg_oldest_5)

67.0